services:
  frontend:
    image: node:lts-alpine
    working_dir:  /front
    volumes:
      - ./:/front
    ports:
      - "80:80"
    depends_on:
      - db
      - backend

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/back
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres
    working_dir:  /db
    volumes:
      - ./:/db
    environment:
     - POSTGRES_DB=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
