services:
  frontend:
    image: node:lts-alpine
    volumes:
      - ./vuejs/data:/data
    ports:
      - 80:80
    depends_on:
      - db
      - backend

  backend:
    build: django
    command: python manage.py
    volumes:
      - ./django/data:/data
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
     - POSTGRES_DB=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
